name: Analyze images (merge → prod)

on:
  push:
    branches: [ main ]

jobs:
  upload-to-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Upload images to S3 (prod prefix)
        run: |
          set -e
          shopt -s nullglob
          for f in images/*.{jpg,jpeg,png,JPG,JPEG,PNG}; do
            b=$(basename "$f")
            echo "Uploading $f -> s3://${{ secrets.S3_BUCKET }}/rekognition-input/prod/$b"
            aws s3 cp "$f" "s3://${{ secrets.S3_BUCKET }}/rekognition-input/prod/$b"
          done
          echo "No images matched pattern" || true

      # --- Optional validation ---
      - name: Validate DynamoDB writes (prod)
        if: always()
        run: |
          set -e
          sleep 8
          shopt -s nullglob
          for f in images/*.{jpg,jpeg,png,JPG,JPEG,PNG}; do
            b=$(basename "$f")
            key="rekognition-input/prod/$b"
            echo "Checking DynamoDB for $key"
            aws dynamodb query \
              --table-name "${{ secrets.DYNAMODB_TABLE_PROD }}" \
              --key-condition-expression "filename = :f" \
              --expression-attribute-values "{\":f\":{\"S\":\"$key\"}}" \
              --output table || true
          done