name: Analyze images (PR → beta)

on:
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Run Rekognition analyzer (beta)
        env:
          AWS_REGION:      ${{ secrets.AWS_REGION }}
          S3_BUCKET:       ${{ secrets.S3_BUCKET }}
          DYNAMODB_TABLE:  ${{ secrets.DYNAMODB_TABLE_BETA }}
          GITHUB_REF_NAME: ${{ github.head_ref }}
        run: python analyze_image.py